# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/louis/c_project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/louis/c_project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	cd /home/louis/c_project && /usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	cd /home/louis/c_project && /usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/louis/c_project/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# The main all target
all: cmake_check_build_system
	cd /home/louis/c_project && $(CMAKE_COMMAND) -E cmake_progress_start /home/louis/c_project/CMakeFiles /home/louis/c_project/final_proj//CMakeFiles/progress.marks
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 final_proj/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/louis/c_project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 final_proj/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 final_proj/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 final_proj/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/louis/c_project && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
final_proj/CMakeFiles/rental_lib.dir/rule:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 final_proj/CMakeFiles/rental_lib.dir/rule
.PHONY : final_proj/CMakeFiles/rental_lib.dir/rule

# Convenience name for target.
rental_lib: final_proj/CMakeFiles/rental_lib.dir/rule

.PHONY : rental_lib

# fast build rule for target.
rental_lib/fast:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/rental_lib.dir/build.make final_proj/CMakeFiles/rental_lib.dir/build
.PHONY : rental_lib/fast

# Convenience name for target.
final_proj/CMakeFiles/map_lib.dir/rule:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 final_proj/CMakeFiles/map_lib.dir/rule
.PHONY : final_proj/CMakeFiles/map_lib.dir/rule

# Convenience name for target.
map_lib: final_proj/CMakeFiles/map_lib.dir/rule

.PHONY : map_lib

# fast build rule for target.
map_lib/fast:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/map_lib.dir/build.make final_proj/CMakeFiles/map_lib.dir/build
.PHONY : map_lib/fast

# Convenience name for target.
final_proj/CMakeFiles/renter_lib.dir/rule:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 final_proj/CMakeFiles/renter_lib.dir/rule
.PHONY : final_proj/CMakeFiles/renter_lib.dir/rule

# Convenience name for target.
renter_lib: final_proj/CMakeFiles/renter_lib.dir/rule

.PHONY : renter_lib

# fast build rule for target.
renter_lib/fast:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/renter_lib.dir/build.make final_proj/CMakeFiles/renter_lib.dir/build
.PHONY : renter_lib/fast

# Convenience name for target.
final_proj/CMakeFiles/107033237_proj.dir/rule:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 final_proj/CMakeFiles/107033237_proj.dir/rule
.PHONY : final_proj/CMakeFiles/107033237_proj.dir/rule

# Convenience name for target.
107033237_proj: final_proj/CMakeFiles/107033237_proj.dir/rule

.PHONY : 107033237_proj

# fast build rule for target.
107033237_proj/fast:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/107033237_proj.dir/build.make final_proj/CMakeFiles/107033237_proj.dir/build
.PHONY : 107033237_proj/fast

include/bike.o: include/bike.cpp.o

.PHONY : include/bike.o

# target to build an object file
include/bike.cpp.o:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/rental_lib.dir/build.make final_proj/CMakeFiles/rental_lib.dir/include/bike.cpp.o
.PHONY : include/bike.cpp.o

include/bike.i: include/bike.cpp.i

.PHONY : include/bike.i

# target to preprocess a source file
include/bike.cpp.i:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/rental_lib.dir/build.make final_proj/CMakeFiles/rental_lib.dir/include/bike.cpp.i
.PHONY : include/bike.cpp.i

include/bike.s: include/bike.cpp.s

.PHONY : include/bike.s

# target to generate assembly for a file
include/bike.cpp.s:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/rental_lib.dir/build.make final_proj/CMakeFiles/rental_lib.dir/include/bike.cpp.s
.PHONY : include/bike.cpp.s

include/map.o: include/map.cpp.o

.PHONY : include/map.o

# target to build an object file
include/map.cpp.o:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/map_lib.dir/build.make final_proj/CMakeFiles/map_lib.dir/include/map.cpp.o
.PHONY : include/map.cpp.o

include/map.i: include/map.cpp.i

.PHONY : include/map.i

# target to preprocess a source file
include/map.cpp.i:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/map_lib.dir/build.make final_proj/CMakeFiles/map_lib.dir/include/map.cpp.i
.PHONY : include/map.cpp.i

include/map.s: include/map.cpp.s

.PHONY : include/map.s

# target to generate assembly for a file
include/map.cpp.s:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/map_lib.dir/build.make final_proj/CMakeFiles/map_lib.dir/include/map.cpp.s
.PHONY : include/map.cpp.s

include/rental.o: include/rental.cpp.o

.PHONY : include/rental.o

# target to build an object file
include/rental.cpp.o:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/rental_lib.dir/build.make final_proj/CMakeFiles/rental_lib.dir/include/rental.cpp.o
.PHONY : include/rental.cpp.o

include/rental.i: include/rental.cpp.i

.PHONY : include/rental.i

# target to preprocess a source file
include/rental.cpp.i:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/rental_lib.dir/build.make final_proj/CMakeFiles/rental_lib.dir/include/rental.cpp.i
.PHONY : include/rental.cpp.i

include/rental.s: include/rental.cpp.s

.PHONY : include/rental.s

# target to generate assembly for a file
include/rental.cpp.s:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/rental_lib.dir/build.make final_proj/CMakeFiles/rental_lib.dir/include/rental.cpp.s
.PHONY : include/rental.cpp.s

include/renter.o: include/renter.cpp.o

.PHONY : include/renter.o

# target to build an object file
include/renter.cpp.o:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/renter_lib.dir/build.make final_proj/CMakeFiles/renter_lib.dir/include/renter.cpp.o
.PHONY : include/renter.cpp.o

include/renter.i: include/renter.cpp.i

.PHONY : include/renter.i

# target to preprocess a source file
include/renter.cpp.i:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/renter_lib.dir/build.make final_proj/CMakeFiles/renter_lib.dir/include/renter.cpp.i
.PHONY : include/renter.cpp.i

include/renter.s: include/renter.cpp.s

.PHONY : include/renter.s

# target to generate assembly for a file
include/renter.cpp.s:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/renter_lib.dir/build.make final_proj/CMakeFiles/renter_lib.dir/include/renter.cpp.s
.PHONY : include/renter.cpp.s

src/107033237_proj.o: src/107033237_proj.cpp.o

.PHONY : src/107033237_proj.o

# target to build an object file
src/107033237_proj.cpp.o:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/107033237_proj.dir/build.make final_proj/CMakeFiles/107033237_proj.dir/src/107033237_proj.cpp.o
.PHONY : src/107033237_proj.cpp.o

src/107033237_proj.i: src/107033237_proj.cpp.i

.PHONY : src/107033237_proj.i

# target to preprocess a source file
src/107033237_proj.cpp.i:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/107033237_proj.dir/build.make final_proj/CMakeFiles/107033237_proj.dir/src/107033237_proj.cpp.i
.PHONY : src/107033237_proj.cpp.i

src/107033237_proj.s: src/107033237_proj.cpp.s

.PHONY : src/107033237_proj.s

# target to generate assembly for a file
src/107033237_proj.cpp.s:
	cd /home/louis/c_project && $(MAKE) $(MAKESILENT) -f final_proj/CMakeFiles/107033237_proj.dir/build.make final_proj/CMakeFiles/107033237_proj.dir/src/107033237_proj.cpp.s
.PHONY : src/107033237_proj.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... 107033237_proj"
	@echo "... map_lib"
	@echo "... rental_lib"
	@echo "... renter_lib"
	@echo "... include/bike.o"
	@echo "... include/bike.i"
	@echo "... include/bike.s"
	@echo "... include/map.o"
	@echo "... include/map.i"
	@echo "... include/map.s"
	@echo "... include/rental.o"
	@echo "... include/rental.i"
	@echo "... include/rental.s"
	@echo "... include/renter.o"
	@echo "... include/renter.i"
	@echo "... include/renter.s"
	@echo "... src/107033237_proj.o"
	@echo "... src/107033237_proj.i"
	@echo "... src/107033237_proj.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/louis/c_project && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

